//SET PRODUCT PAGE
export const SET_PRODUCT_PAGE = "SET_PRODUCT_PAGE";
export const SET_PRODUCT_PAGE_FALSE = "SET_PRODUCT_PAGE_FALSE";
//AUTH
export const AUTH_START = "AUTH_START";
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

//FORM SUBMISSION TO ADD PRODUCT

export const ADD_PRODUCT_FORM_SUBMISSION_START = "ADD_PRODUCT_FORM_SUBMISSION_START";
export const ADD_PRODUCT_FORM_SUBMISSION_SUCCESS = "ADD_PRODUCT_FORM_SUBMISSION_SUCCESS";
export const ADD_PRODUCT_FORM_SUBMISSION_FAIL = "ADD_PRODUCT_FORM_SUBMISSION_FAIL";

//FETCH BOOK ON A PAGE
export const FETCH_BOOK_ON_PAGE_START = "FETCH_BOOK_ON_PAGE_START";
export const FETCH_BOOK_ON_PAGE_SUCCESS = "FETCH_BOOK_ON_PAGE_SUCCESS";
export const FETCH_BOOK_ON_PAGE_FAIL = "FETCH_BOOK_ON_PAGE_FAIL";

//ADD TO CART
export const ADD_PRODUCT_TO_CART_START = "ADD_PRODUCT_TO_CART_START";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL";
export const RESET_PRODUCT_ADDED_TO_CART = "RESET_PRODUCT_ADDED_TO_CART";
//FETCH CART
export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";

//REMOVE FROM CART
export const REMOVE_FROM_CART_START = "REMOVE_FROM_CART_START";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

//FETCH USER PRODUCTS
export const FETCH_USER_PRODUCTS_START = "FETCH_USER_PRODUCTS_START";
export const FETCH_USER_PRODUCTS_SUCCESS = "FETCH_USER_PRODUCTS_SUCCESS";
export const FETCH_USER_PRODUCTS_FAIL = "FETCH_USER_PRODUCTS_FAIL";
//FETCH PRODUCT
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
//FETCH SEARCH RESULTS
export const FETCH_SEARCH_RESULTS_START = "FETCH_SEARCH_RESULTS_START";
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
export const FETCH_SEARCH_RESULTS_FAIL = "FETCH_SEARCH_RESULTS_FAIL";
//GET TRENDING
export const FETCH_TRENDING_START = "FETCH_TRENDING_START";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_TRENDING_FAIL = "FETCH_TRENDING_FAIL";
//GET RECOMMENDED
export const FETCH_RECOMMENDED_START = "FETCH_RECOMMENDED_START";
export const FETCH_RECOMMENDED_SUCCESS = "FETCH_RECOMMENDED_SUCCESS";
export const FETCH_RECOMMENDED_FAIL = "FETCH_RECOMMENDED_FAIL";
//GET RECENTLY ADDED
//DELETE USER PRODUCT
export const DELETE_USER_PRODUCT_START = "DELETE_USER_PRODUCT_START";
export const DELETE_USER_PRODUCT_SUCCESS = "DELETE_USER_PRODUCT_SUCCESS";
export const DELETE_USER_PRODUCT_FAIL = "DELETE_USER_PRODUCT_FAIL";
//RESET USER DELETE PRODUCT
export const RESET_USER_DELETE_PRODUCT = "RESET_USER_DELETE_PRODUCT";
//FETCH BOOK TO EDIT
export const FETCH_BOOK_TO_EDIT_START = "FETCH_BOOK_TO_EDIT_START";
export const FETCH_BOOK_TO_EDIT_SUCCESS = "FETCH_BOOK_TO_EDIT_SUCCESS";
export const FETCH_BOOK_TO_EDIT_FAIL = "FETCH_BOOK_TO_EDIT_FAIL";
//EDIT BOOK
export const EDIT_USER_BOOK_START = "EDIT_USER_BOOK_START";
export const EDIT_USER_BOOK_SUCCESS = "EDIT_USER_BOOK_SUCCESS";
export const EDIT_USER_BOOK_FAIL = "EDIT_USER_BOOK_FAIL";

//CHECKOUT BOOK
export const CHECKOUT_CART_START = "CHECKOUT_CART_START";
export const CHECKOUT_CART_SUCCESS = "CHECKOUT_CART_SUCCESS";
export const CHECKOUT_CART_FAIL = "CHECKOUT_CART_FAIL";

//RESULT FETCH
// export const ESULT_FETCH_STARTR = "RESULT_FETCH_START";
// export const RESULT_FETCH_SUCCESS = "RESULT_FETCH_SUCCESS";
// export const RESULT_FETCH_FAIL = "RESULT_FETCH_FAIL";

// export const SET_NAVIGATION = 'SET_NAVIGATION';

// export const EVENT_FETCH_START = "EVENT_FETCH_START";
// export const EVENT_FETCH_SUCCESS = "EVENT_FETCH_SUCCESS";
// export const EVENT_FETCH_FAIL = "EVENT_FETCH_FAIL";

// export const EVENT_ENROLL_START = "EVENT_ENROLL_START";
// export const EVENT_ENROLL_SUCCESS = "EVENT_ENROLL_SUCCESS";
// export const EVENT_ENROLL_FAIL = "EVENT_ENROLL_FAIL";

// export const FETCH_ENROL_EVENT_START = "FETCH_ENROL_EVENT_START";
// export const FETCH_ENROL_EVENT_SUCCESS = "FETCH_ENROL_EVENT_SUCCESS";
// export const FETCH_ENROL_EVENT_FAIL = "FETCH_ENROL_EVENT_FAIL";

// export const CHECK_ENROLLMENT_START = "CHECK_ENROLLMENT_START";
// export const CHECK_ENROLLMENT_SUCCESS = "CHECK_ENROLLMENT_SUCCESS";
// export const CHECK_ENROLLMENT_FAIL = "CHECK_ENROLLMENT_FAIL";

// export const ENROLLED_EVENT_FETCH_START = "ENROLLED_EVENT_FETCH_START";
// export const ENROLLED_EVENT_FETCH_SUCCESS = "ENROLLED_EVENT_FETCH_SUCCESS";
// export const ENROLLED_EVENT_FETCH_FAIL = "ENROLLED_EVENT_FETCH_FAIL";

// export const FETCH_USER_EVENT_START = "FETCH_USER_EVENT_START";
// export const FETCH_USER_EVENT_SUCCESS = "FETCH_USER_EVENT_SUCCESS";
// export const FETCH_USER_EVENT_FAIL = "FETCH_USER_EVENT_FAIL";
